Snapshot from automake-1.8.tar.bz2

diff --git a/tests/defs.in b/tests/defs.in
--- a/tests/defs.in
+++ b/tests/defs.in
@@ -1,4 +1,6 @@
 # -*- shell-script -*-
+# @configure_input@
+#
 # Copyright (C) 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003
 # Free Software Foundation, Inc.
 #
@@ -21,6 +23,18 @@
 
 # Defines for Automake testing environment.
 # Tom Tromey <tromey@cygnus.com>
+
+# Be Bourne compatible.
+# (Snippet copied from configure's initialization in Autoconf 2.57.)
+if test -n "${ZSH_VERSION+set}" && (emulate sh) >/dev/null 2>&1; then
+  emulate sh
+  NULLCMD=:
+  # Zsh 3.x and 4.x performs word splitting on ${1+"$@"}, which
+  # is contrary to our usage.  Disable this feature.
+  alias -g '${1+"$@"}'='"$@"'
+elif test -n "${BASH_VERSION+set}" && (set -o posix) >/dev/null 2>&1; then
+  set -o posix
+fi
 
 # Ensure we are running from the right directory.
 test -f ./defs || {
@@ -50,13 +64,27 @@ test -z "$VERBOSE" && {
    exec > /dev/null 2>&1
 }
 
+# Make sure we override the user shell.
 SHELL='@SHELL@'
+export SHELL
 # User can override various tools used.
 test -z "$PERL" && PERL='@PERL@'
 test -z "$MAKE" && MAKE=make
 test -z "$AUTOCONF" && AUTOCONF="@AUTOCONF@"
 test -z "$AUTOHEADER" && AUTOHEADER="@AUTOHEADER@"
 test -z "$AUTOUPDATE" && AUTOUPDATE=autoupdate
+test -z "$MISSING" && MISSING=`pwd`/../lib/missing
+test -z "$ACLOCAL" && ACLOCAL="aclocal-@APIVERSION@"
+# See how Automake should be run.  We put --foreign as the default
+# strictness to avoid having to create lots and lots of files.  A test
+# can override this by specifying a different strictness.  Use -Wall
+# -Werror by default.  Tests for which this is inappropriate
+# (e.g. when testing that a warning is enabled by a specific switch)
+# should use -Wnone or/and -Wno-error
+test -z "$AUTOMAKE" && AUTOMAKE="automake-@APIVERSION@ --foreign -Werror -Wall"
+
+PATH=`pwd`:$PATH
+echo $PATH
 
 if test -n "$required"
 then
@@ -70,6 +98,11 @@ then
 	export YACC
 	echo "$me: running bison --version"
 	( bison --version ) || exit 77
+	;;
+      bzip2)
+	# Do not use --version, bzip2 still tries to compress stdin.
+	echo "$me: running bzip2 --help"
+	( bzip2 --help ) || exit 77
 	;;
       etags)
 	# Exuberant Ctags will create a TAGS file even
@@ -113,6 +146,11 @@ then
       makedepend)
 	echo "$me: running makedepend -f-"
 	( makedepend -f- ) || exit 77
+	;;
+      makeinfo-html)
+	# Make sure makeinfo understands --html.
+	echo "$me: running makeinfo --html --version"
+	( makeinfo --html --version ) || exit 77
 	;;
       non-root)
 	# Skip this test case if the user is root.
@@ -188,7 +226,7 @@ rm -rf testSubDir > /dev/null 2>&1
 mkdir testSubDir
 
 # Copy in some files we need.
-for file in install-sh mkinstalldirs missing depcomp; do
+for file in install-sh missing depcomp; do
    cp $srcdir/../lib/$file testSubDir/$file || exit 1
 done
 
@@ -215,28 +253,6 @@ unset MAKELEVEL
 unset DESTDIR
 
 echo "=== Running test $0"
-
-# See how Automake should be run.  We put --foreign as the default
-# strictness to avoid having to create lots and lots of files.  A test
-# can override this by specifying a different strictness.
-if test -z "$AUTOMAKE"; then
-   perllibdir=$srcdir/../lib
-   export perllibdir
-   # Use -Wall -Werror by default.  Tests for which this is inappropriate
-   # (e.g. when testing that a warning is enabled by a specific switch)
-   # should use -Wnone or/and -Wno-error
-   AUTOMAKE="$PERL `pwd`/../../automake --libdir=$srcdir/../lib --foreign -Werror -Wall"
-fi
-
-# See how aclocal should be run.
-if test -z "$ACLOCAL"; then
-   perllibdir=$srcdir/../lib
-   export perllibdir
-   # Most of the files are in $srcdir/../m4.  However amversion.m4 is
-   # generated in ../m4, so we include that directory in the search
-   # path too.
-   ACLOCAL="$PERL `pwd`/../../aclocal -I `pwd`/../../m4 --acdir=$srcdir/../m4"
-fi
 
 # We might need extra macros, e.g., from Libtool or Gettext.
 # Find them on the system.
@@ -275,25 +291,44 @@ case $required in
     ;;
 esac
 
-# Export AUTOMAKE and ACLOCAL so that rebuild rules in Makefiles
-# generated for the tests do not use the installed tools.
-export AUTOMAKE ACLOCAL
-
 # POSIX no longer requires 'egrep' and 'fgrep',
 # but some hosts lack 'grep -E' and 'grep -F'.
 EGREP='@EGREP@'
 FGREP='@FGREP@'
 
-# On Windows '95, '98 and ME, files modifications have 2-seconds
-# granularity and can be up to 3 seconds in the future w.r.t. the
-# system clock.  When it is important to ensure one file is older
-# than another we wait at least 5 seconds between creations.
-sleep='sleep 5'
+# The amount we should wait after modifying files depends on the platform.
+# For instance, Windows '95, '98 and ME have 2-second granularity
+# and can be up to 3 seconds in the future w.r.t. the system clock.
+sleep='sleep @MODIFICATION_DELAY@'
 
 # The tests call `make -e' but we do not want $srcdir from the environment
 # to override the definition from the Makefile.
 testsrcdir=$srcdir
 unset srcdir
+
+# AUTOMAKE_run status [options...]
+# --------------------------------
+# Run Automake with OPTIONS, and fail if automake
+# does not exit with STATUS.
+AUTOMAKE_run ()
+{
+  expected_exitcode=$1
+  shift
+  exitcode=0
+  $AUTOMAKE ${1+"$@"} 2>stderr >stdout || exitcode=$?
+  cat stderr
+  cat stdout
+  test $exitcode = $expected_exitcode || exit 1
+}
+
+# AUTOMAKE_fails [options...]
+# ---------------------------
+# Run Automake with OPTIONS, and fail if automake
+# does not exit with STATUS.
+AUTOMAKE_fails ()
+{
+  AUTOMAKE_run 1 ${1+"$@"}
+}
 
 # Turn on shell traces when VERBOSE=x.
 if test "x$VERBOSE" = xx; then
